openapi: 3.0.0
info:
  title: The coach API service
  description: A simple service to manage coaches and their calendars
  version: 1.0.0
servers:
  - url: https://agenttest.in.ngrok.io/api
    description: The repair api server
paths:
  /repairs:
    get:
      operationId: listRepairs
      summary: List all repairs
      description: Returns a list of repairs with their details and images
      parameters:
        - name: assignedTo
          in: query
          description: Filter repairs by who they're assigned to
          schema:
            type: string
          required: false
      responses:
        "200":
          description: A list of repairs
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier of the repair
                        title:
                          type: string
                          description: The short summary of the repair
                        description:
                          type: string
                          description: The detailed description of the repair
                        assignedTo:
                          type: string
                          description: The user who is responsible for the repair
                        date:
                          type: string
                          format: date-time
                          description: The date and time when the repair is scheduled or completed
                        image:
                          type: string
                          format: uri
                          description: The URL of the image of the item to be repaired or the repair process
  /coach/{id}:
    get:
      operationId: getCoachDetails
      summary: Get details of a coach by ID
      description: Returns coach details including first name, last name, email, phone number, image URL, and timezone
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single coach
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Status message
                  error:
                    type: boolean
                    description: Error flag
                  data:
                    type: object
                    properties:
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      phone_number:
                        type: string
                      image_url:
                        type: string
                        format: uri
                      timezone:
                        type: string
        "404":
          description: Coach not found
  /coach/{coach_id}/events:
    get:
      operationId: getCoachEvents
      summary: Get events for a coach by date range and time zone
      description: Returns events for a coach within a specific date range and time zone
      parameters:
        - name: coach_id
          in: path
          required: true
          schema:
            type: integer
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: time_zone
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Coach events retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: boolean
                  data:
                    type: object
                    properties:
                      events:
                        type: object
                        additionalProperties:
                          type: array
                          items:
                            type: string
                            description: Time range of the event
                      coach_time_zone:
                        type: string
        "400":
          description: Invalid request parameters
        "500":
          description: Failed to retrieve events
  /coach/calendar/event:
    post:
      operationId: createEvent
      summary: Create a new event for a coach
      description: This endpoint allows you to create a new event for a coach, including event details and user information.
      requestBody:
        description: JSON payload containing event details and user information.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coach_id:
                  type: integer
                  description: The unique ID of the coach
                coach_time_zone:
                  type: string
                  description: Time zone of the coach
                company_id:
                  type: integer
                  description: The company ID associated with the event
                event:
                  type: object
                  description: Event details
                  properties:
                    end_time:
                      type: string
                      format: date-time
                      description: End time of the event
                    start_time:
                      type: string
                      format: date-time
                      description: Start time of the event
                    is_consented:
                      type: boolean
                      description: Whether the user has given consent for the event
                    is_credit_deducted:
                      type: boolean
                      description: Whether credit has been deducted for the session
                    meeting_id:
                      type: integer
                      nullable: true
                      description: The meeting ID, if applicable
                    reschedule:
                      type: boolean
                      description: Whether this event is a rescheduled event
                    tripartite_email:
                      type: string
                      format: email
                      description: The tripartite email address, if applicable
                user:
                  type: object
                  description: Information about the user booking the event
                  properties:
                    email:
                      type: string
                      format: email
                      description: Email of the user
                    first_name:
                      type: string
                      description: First name of the user
                    last_name:
                      type: string
                      description: Last name of the user
                    medium:
                      type: string
                      description: Medium through which the event is booked (e.g., website)
                    user_comment:
                      type: string
                      description: User comments associated with the event
                user_time_zone:
                  type: string
                  description: Time zone of the user

      responses:
        "200":
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Event created successfully"
                  data:
                    type: object
                    properties:
                      coach_id:
                        type: integer
                        description: The ID of the coach associated with the event
                      event:
                        type: object
                        properties:
                          start_time:
                            type: string
                            format: date-time
                            description: Start time of the event
                          end_time:
                            type: string
                            format: date-time
                            description: End time of the event
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Missing required fields: coach_id, event, and user are required"
                  error:
                    type: boolean
                    example: true
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Failed to create event"
                  error:
                    type: boolean
                    example: true
